name: Filter Delayed GPS Points

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Fetch and filter delayed points
        run: |
          curl -s https://raw.githubusercontent.com/ajthisway/aj-map-live/main/locations.json -o all.json

          cat <<EOF > filter.py
import json, time, datetime

with open("all.json") as f:
    data = json.load(f)

now = time.time()
filtered = []

for point in data:
    ts = point.get("timestamp")

    # Convert ISO 8601 with milliseconds to Unix timestamp
    if isinstance(ts, str):
        try:
            dt = datetime.datetime.strptime(ts, "%Y-%m-%dT%H:%M:%S.%fZ")
            ts = time.mktime(dt.timetuple())
        except Exception:
            continue

    if isinstance(ts, (int, float)) and ts < now - 86400:
        filtered.append(point)

with open("delayed_locations.json", "w") as f:
    json.dump(filtered, f, indent=2)
EOF

          python3 filter.py

      - name: Commit and push the updated file
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "aj-map-bot"
          git config --global user.email "aj@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add delayed_locations.json
          git commit -m "Update delayed map" || echo "No changes"
          git push origin main
