- name: Fetch and filter delayed points
  run: |
    curl -s https://raw.githubusercontent.com/ajthisway/aj-map-live/main/locations.json -o all.json

    cat <<EOF > filter.py
import json, time, datetime

with open("all.json") as f:
    data = json.load(f)

now = time.time()
filtered = []

for point in data:
    ts = point.get("timestamp")

    # Convert ISO 8601 to Unix timestamp if it's a string
    if isinstance(ts, str):
        try:
            dt = datetime.datetime.strptime(ts, "%Y-%m-%dT%H:%M:%S.%fZ")
            ts = time.mktime(dt.timetuple())
        except Exception as e:
            continue  # skip point if timestamp can't be parsed

    if isinstance(ts, (int, float)) and ts < now - 86400:
        filtered.append(point)

with open("delayed_locations.json", "w") as f:
    json.dump(filtered, f, indent=2)
EOF

    python3 filter.py
